services:
  xdmod_db:
    image: mariadb:latest
    container_name: xdmod_db
    restart: no
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: xdmod
      MYSQL_USER: xdmod
      MYSQL_PASSWORD: your_root_password
    volumes:
      - ./xdmod-db-setup.sql:/docker-entrypoint-initdb.d/xdmod-db-setup.sql

  xdmod_container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xdmod_container
    restart: no
    ports:
      - 8080:8080
      - 443:443
    depends_on:
      - xdmod_db
    environment:
      DB_HOST: xdmod_db
      DB_PORT: 3306
      DB_USER: xdmod
      DB_PASSWORD: your_root_password